[project]
name = "apnea_trainer"
version = "0.1.0"
description = "A command-line timer for apnea training sessions"
authors = [
    {name = "Paul S. Schweigert", email = "paul@paulschweigert.com"}
]
dependencies = [
    "tomli>=2.0.1",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "Apache-2.0"}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
apnea-trainer = "apnea_trainer.timer:main"
apnea-trainer-gui = "apnea_trainer.gui:main"

[tool.hatch.build.targets.wheel]
packages = ["src/apnea_trainer"]

[tool.hatch.metadata]
allow-direct-references = true 